#!/usr/bin/python3

#==========================================================================================#
#
# CODE DESCRIPTION:
#
# This code processes the gradient files generated by the
# QNDM and DM methods. This code produces:
#
# - pauli_mean_dm.txt     : value N_ps and the mean for the DM method
# - pauli_mean_qndm.txt   : value N_ps and the mean for the QNDM method
# - pauli_variance_dm.txt : value N_ps and the variance for the DM method
# - pauli_variance_dm.txt : value Nl_ps and the variance for the QNDM method
# - bias_dm.txt           : value N_ps and the bias for the DM method
# - bias_qndm.txt         : value N_ps and the bias for the QNDM method
# - var_dm.txt            : value N_ps and the variance for the DM method
# - var_qndm.txt          : value N_ps and the variance for the QNDM method
# - oom_dm.txt            : value N_ps and the order of magnitude for the DM method
# - oom_qndm.txt          : value N_ps and the order of magnitude for the QNDM method
#
# In the folder structure, this code works at the lowest level of the tree.
#
#==========================================================================================#

# 
# IMPORTATION OF LIBRARIES
#----------------------------------------------------------#

import os
import sys
import numpy as np
import matplotlib.pyplot as plt


#==========================================================#
#
# FInd the valid directories containing the set_X folders
# excluding the hamiltonians (MUST be excluded)
#
#==========================================================#

def find_valid_directories(base_dir):
    valid_dirs = []
    for root, dirs, _ in os.walk(base_dir):
        if "hamiltonians" in root:
            continue  # Salta la cartella hamiltonians
        
        # Controlla se esiste almeno una cartella che inizia con "set_"
        set_dirs = [d for d in dirs if d.startswith("set_")]
        for set_dir in set_dirs:
            valid_dirs.append(os.path.join(root, set_dir))
    
    return valid_dirs


#==========================================================#
#
# Legge le colonne di un file .txt (tipo quello dei gradienti) 
# e le converte in array. THere are both the codes for the
# first and the second column.
#
#==========================================================#

def read_first_column(file_path, has_header=True):
    """
    Legge la prima colonna di un file di testo, ignorando l'eventuale intestazione e righe non numeriche.
    Restituisce un array numpy con i numeri letti.
    """
    with open(file_path, 'r') as f:
        lines = f.readlines()
    
    # Se c'è un'intestazione, rimuovila
    if has_header:
        lines = lines[1:]

    # Converti le righe in numeri, saltando quelle non valide
    data = []
    for line in lines:
        parts = line.split()
        if parts:  # Controlla che la riga non sia vuota
            try:
                data.append(float(parts[0]))  # Prova a convertire la prima colonna in float
            except ValueError:
                print(f"Attenzione: riga ignorata in {file_path}: {line.strip()}")  # Debugging
                continue  # Salta la riga se non è numerica
    
    return np.array(data)


def read_second_column(file_path, has_header=True):
    """
    Legge la seconda colonna di un file di testo, ignorando l'eventuale intestazione e righe non numeriche.
    Restituisce un array numpy con i numeri letti.
    """
    with open(file_path, 'r') as f:
        lines = f.readlines()
    
    # Se c'è un'intestazione, rimuovila
    if has_header:
        lines = lines[1:]
    
    # Converti le righe in numeri, saltando quelle non valide
    data = []
    for line in lines:
        parts = line.split()  # Suddivide la riga in parti (separate da spazi)
        if len(parts) >= 2:  # Controlla che ci siano almeno due colonne nella riga
            try:
                data.append(float(parts[1]))  # Prova a convertire la seconda colonna in float
            except ValueError:
                print(f"Attenzione: riga ignorata in {file_path}: {line.strip()}")  # Debugging
                continue  # Salta la riga se non è numerica
    
    return np.array(data)

#==========================================================#
#
# calculate_means_and_vars function. This function calculates
# the means and the variances of the gradients for the DM and
# QNDM methods. The results are saved in the corresponding
# files.
#
#==========================================================#

def calculate_means_and_vars(root_dir):
    for folder_path, _, filenames in os.walk(root_dir):
        if "hamiltonians" in folder_path:
            continue  # Salta la cartella hamiltonians
        
        # Trova il numero di Pauli strings dal percorso
        num_pauli_strings = None
        for part in folder_path.split(os.sep):
            if part.endswith("_pauli_strings"):
                num_pauli_strings = part.split("_")[0]  # Prendi solo il numero
                break
        
        if num_pauli_strings is None:
            continue  # Se non c'è il numero di Pauli strings, salta la cartella

        dm_gradients   = []
        qndm_gradients = []

        # Scan the files in the folder
        for filename in filenames:
            file_path = os.path.join(folder_path, filename)
            if filename.startswith("gradient_dm_shots_") and filename.endswith(".txt"):
                dm_gradients.append(np.loadtxt(file_path, skiprows=1))
            elif filename.startswith("gradient_qndm_shots_") and filename.endswith(".txt"):
                qndm_gradients.append(np.loadtxt(file_path, skiprows=1))
        
        # Calcola media e varianza per ogni componente del gradiente se ci sono dati
        if dm_gradients:
            dm_gradients = np.array(dm_gradients)
            dm_means     = np.mean(dm_gradients, axis=0)
            dm_vars      = np.var(dm_gradients, axis=0)
            np.savetxt(os.path.join(folder_path, "mean_gradient_dm.txt"), np.column_stack((dm_means, dm_vars)), header="mean variance")
        else:
            dm_means, dm_vars = None, None
        
        if qndm_gradients:
            qndm_gradients = np.array(qndm_gradients)
            qndm_means     = np.mean(qndm_gradients, axis=0)
            qndm_vars      = np.var(qndm_gradients, axis=0)
            np.savetxt(os.path.join(folder_path, "mean_gradient_qndm.txt"), np.column_stack((qndm_means, qndm_vars)), header="mean variance")
        else:
            qndm_means, qndm_vars = None, None
        
        # Calcola la media della media per ciascuno
        mean_mean_dm   = np.mean(dm_means)   if dm_means   is not None else 0
        mean_mean_qndm = np.mean(qndm_means) if qndm_means is not None else 0

        # Calcola la varianza media
        mean_var_dm   = np.mean(dm_vars)   if dm_vars   is not None else 0
        mean_var_qndm = np.mean(qndm_vars) if qndm_vars is not None else 0
        
        # Scrivi i risultati nei file corrispondenti
        with open(os.path.join(folder_path, "pauli_mean_dm.txt"), "w") as f:
            f.write("Num_Pauli_Strings\tMean_Mean\n")
            f.write(f"{num_pauli_strings}\t{mean_mean_dm}\n")

        with open(os.path.join(folder_path, "pauli_mean_qndm.txt"), "w") as f:
            f.write("Num_Pauli_Strings\tMean_Mean\n")
            f.write(f"{num_pauli_strings}\t{mean_mean_qndm}\n")

        with open(os.path.join(folder_path, "pauli_variance_dm.txt"), "w") as f:
            f.write("Num_Pauli_Strings\tMean_Variance\n")
            f.write(f"{num_pauli_strings}\t{mean_var_dm}\n")

        with open(os.path.join(folder_path, "pauli_variance_qndm.txt"), "w") as f:
            f.write("Num_Pauli_Strings\tMean_Variance\n")
            f.write(f"{num_pauli_strings}\t{mean_var_qndm}\n")
    
    return (dm_means, dm_vars), (qndm_means, qndm_vars)
'''

def calculate_means_and_vars(root_dir):
    
    mean_dm_list   = []
    mean_qndm_list = []
    
    for folder_path, _, filenames in os.walk(root_dir):
        if "hamiltonians" in folder_path:
            continue  # Salta la cartella hamiltonians
        
        num_pauli_strings = None
        for part in folder_path.split(os.sep):
            if part.endswith("_pauli_strings"):
                try:
                    num_pauli_strings = int(part.split("_")[0])  # Converte in intero per ordinamento numerico
                except ValueError:
                    continue
                break
        
        if num_pauli_strings is None:
            continue

        dm_gradients   = []
        qndm_gradients = []

        for filename in filenames:
            file_path = os.path.join(folder_path, filename)
            if filename.startswith("gradient_dm_shots_") and filename.endswith(".txt"):
                dm_gradients.append(np.loadtxt(file_path, skiprows=1))
            elif filename.startswith("gradient_qndm_shots_") and filename.endswith(".txt"):
                qndm_gradients.append(np.loadtxt(file_path, skiprows=1))
        
        if dm_gradients:
            dm_gradients = np.array(dm_gradients)
            dm_means     = np.mean(dm_gradients, axis=0)
            dm_vars      = np.var(dm_gradients, axis=0)
            np.savetxt(os.path.join(folder_path, "mean_gradient_dm.txt"), np.column_stack((dm_means, dm_vars)), header="mean variance")
            mean_dm_list.append([num_pauli_strings, np.mean(dm_means)])
        
        if qndm_gradients:
            qndm_gradients = np.array(qndm_gradients)
            qndm_means     = np.mean(qndm_gradients, axis=0)
            qndm_vars      = np.var(qndm_gradients, axis=0)
            np.savetxt(os.path.join(folder_path, "mean_gradient_qndm.txt"), np.column_stack((qndm_means, qndm_vars)), header="mean variance")
            mean_qndm_list.append([num_pauli_strings, np.mean(qndm_means)])
    
    # Ordinamento per numero di Pauli strings
    mean_dm_list.sort(key=lambda x: x[0])
    mean_qndm_list.sort(key=lambda x: x[0])

    if mean_dm_list and mean_qndm_list:
        np.savetxt(os.path.join(root_dir, "mean_dm.txt"),   np.array(mean_dm_list), fmt='%d %.6f', header="Num_Pauli_Strings Mean_Mean")
        np.savetxt(os.path.join(root_dir, "mean_qndm.txt"), np.array(mean_qndm_list), fmt='%d %.6f', header="Num_Pauli_Strings Mean_Mean")
    
    return

'''

#==========================================================#
#
# BIAS AND ORDER OF MAGNITUDE CALCULATION
#
#==========================================================#

def calculate_bias_and_oom(root_dir):
    """
    Check the directory and calculate the differences between the gradients and the mean values of the components in modulus.
    """

    set_means = {}  # Dictionary to store the mean square of the differences
    bias_dm   = {}  # Bias for dm
    bias_qndm = {}  # Bias for qndm
    oom_dm    = {}  # Order of magnitude for dm
    oom_qndm  = {}  # Order of magnitude for qndm
    oom_sv    = {}  # Order of magnitude for sv
    var_dm    = {}  # Variance for dm
    var_qndm  = {}  # Variance for qndm

    for dirpath, _, filenames in os.walk(root_dir):
        if "hamiltonians" in dirpath:
            continue

        if {"mean_gradient_dm.txt", "mean_gradient_qndm.txt", "gradient_dm_statevector.txt", "pauli_variance_dm.txt", "pauli_variance_qndm.txt"}.issubset(filenames):
            
            sv_path       = os.path.join(dirpath, "gradient_dm_statevector.txt")

            dm_path       = os.path.join(dirpath, "mean_gradient_dm.txt")
            qndm_path     = os.path.join(dirpath, "mean_gradient_qndm.txt")
            var_dm_path   = os.path.join(dirpath, "mean_gradient_dm.txt")
            var_qndm_path = os.path.join(dirpath, "mean_gradient_qndm.txt")

            dm_data       = read_first_column(dm_path, has_header=True)
            qndm_data     = read_first_column(qndm_path, has_header=True)
            sv_data       = read_first_column(sv_path, has_header=True)
            var_dm_data   = read_second_column(var_dm_path, has_header=True)
            var_qndm_data = read_second_column(var_qndm_path, has_header=True)

            # Check for empty files
            if dm_data.size == 0 or qndm_data.size == 0 or sv_data.size == 0 or var_dm_data.size == 0 or var_qndm_data.size == 0:
                print(f"Error: one or more files in {dirpath} is empty or not legible.")
                continue

            assert len(dm_data) == len(qndm_data) == len(sv_data) == len(var_dm_data) == len(var_qndm_data), "Error: the number of elements in the files is different."
            min_len = min(len(dm_data), len(qndm_data), len(sv_data))
            dm_data, qndm_data, sv_data, var_dm_data, var_qndm_data = dm_data[:min_len], qndm_data[:min_len], sv_data[:min_len], var_dm_data[:min_len], var_qndm_data[:min_len]

            diff_dm_qndm = dm_data   - qndm_data
            diff_dm_sv   = dm_data   - sv_data
            diff_qndm_sv = qndm_data - sv_data

            np.savetxt(os.path.join(dirpath, "gradient_diff_dm_and_qndm.txt"), diff_dm_qndm)
            np.savetxt(os.path.join(dirpath, "gradient_diff_dm_and_sv.txt")  , diff_dm_sv)
            np.savetxt(os.path.join(dirpath, "gradient_diff_qndm_and_sv.txt"), diff_qndm_sv)

            # Extract the number of Pauli strings from the directory name
            set_name = os.path.basename(dirpath)
            N_ps = int(''.join(filter(str.isdigit, set_name)))

            # Calculate the mean square of the differences 
            mean_square_dm_qndm = np.mean(diff_dm_qndm**2)  # mean square of the differences between dm and qndm
            mean_square_dm_sv   = np.mean(diff_dm_sv**2)    # mean square of the differences between dm and sv
            mean_square_qndm_sv = np.mean(diff_qndm_sv**2)  # mean square of the differences between qndm and sv

            set_means[N_ps] = (mean_square_dm_qndm, mean_square_dm_sv, mean_square_qndm_sv)
            bias_dm[N_ps]   = mean_square_dm_sv
            bias_qndm[N_ps] = mean_square_qndm_sv

            # Calculate the order of magnitude (mean absolute value)
            oom_dm[N_ps]   = np.mean(np.abs(dm_data))
            oom_qndm[N_ps] = np.mean(np.abs(qndm_data))
            oom_sv[N_ps]   = np.mean(np.abs(sv_data))

            # Calculate variance mean values
            var_dm[N_ps]   = np.mean(var_dm_data)
            var_qndm[N_ps] = np.mean(var_qndm_data)

    if not set_means:
        print("No found 'set_' in the directory. Exiting...")
        return

    sorted_N_ps = sorted(set_means.keys())

    bias_dm_content   = "N_ps\tBias\n"
    bias_qndm_content = "N_ps\tBias\n"
    oom_dm_content    = "N_ps\tOoM\n"
    oom_qndm_content  = "N_ps\tOoM\n"
    oom_sv_content    = "N_ps\tOoM\n"
    var_dm_content    = "N_ps\tVariance\n"
    var_qndm_content  = "N_ps\tVariance\n"
    mse_dm_content    = "N_ps\tMSE\n"
    mse_qndm_content  = "N_ps\tMSE\n"

    for N_ps in sorted_N_ps:
        bias_val_dm   = bias_dm.get(N_ps, 0)
        bias_val_qndm = bias_qndm.get(N_ps, 0)
        var_val_dm    = var_dm.get(N_ps, 0)
        var_val_qndm  = var_qndm.get(N_ps, 0)

        mse_dm   = bias_val_dm   + var_val_dm
        mse_qndm = bias_val_qndm + var_val_qndm

        bias_dm_content   += f"{N_ps}\t{bias_val_dm:.6f}\n"
        bias_qndm_content += f"{N_ps}\t{bias_val_qndm:.6f}\n"
        oom_dm_content    += f"{N_ps}\t{oom_dm.get(N_ps, 0):.6f}\n"
        oom_qndm_content  += f"{N_ps}\t{oom_qndm.get(N_ps, 0):.6f}\n"
        oom_sv_content    += f"{N_ps}\t{oom_sv.get(N_ps, 0):.6f}\n"
        var_dm_content    += f"{N_ps}\t{var_val_dm:.6f}\n"
        var_qndm_content  += f"{N_ps}\t{var_val_qndm:.6f}\n"
        mse_dm_content    += f"{N_ps}\t{mse_dm:.6f}\n"
        mse_qndm_content  += f"{N_ps}\t{mse_qndm:.6f}\n"

    # Saving into files
    with open(os.path.join(root_dir, "bias_dm.txt"), "w") as f:
        f.write(bias_dm_content)

    with open(os.path.join(root_dir, "bias_qndm.txt"), "w") as f:
        f.write(bias_qndm_content)

    with open(os.path.join(root_dir, "oom_dm.txt"), "w") as f:
        f.write(oom_dm_content)

    with open(os.path.join(root_dir, "oom_qndm.txt"), "w") as f:
        f.write(oom_qndm_content)

    with open(os.path.join(root_dir, "oom_sv.txt"), "w") as f:
        f.write(oom_sv_content)

    with open(os.path.join(root_dir, "var_dm.txt"), "w") as f:
        f.write(var_dm_content)

    with open(os.path.join(root_dir, "var_qndm.txt"), "w") as f:
        f.write(var_qndm_content)

    with open(os.path.join(root_dir, "MSE_dm.txt"), "w") as f:
        f.write(mse_dm_content)

    with open(os.path.join(root_dir, "MSE_qndm.txt"), "w") as f:
        f.write(mse_qndm_content)

    print("All data saved.")

    


#==========================================================#
#
# MAIN CODE
#==========================================================#

# base directory 
base_directory = "/home/mele/cacchio/qndm/test_scripts/check_error/tmp_2"

# list of the valid directories
directories_to_process = find_valid_directories(base_directory)



# Esegui le funzioni per ogni cartella valida
for directory in directories_to_process:
    calculate_means_and_vars(directory)

# Esegui le funzioni per ogni cartella valida
for directory in directories_to_process:
    calculate_bias_and_oom(directory)
